modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="warmod"
version="1.0.0"
displayName="Warmod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Daniel Chen, MCreator"

[[dependencies.warmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




